services:
  app:
    build:
      context: .
      target: production-stage
    ports:
      - "80:80"
    restart: always

  # --- Si necesitas desarrollo local con Hot Reload ---
  # dev:
  #   image: node:20-alpine
  #   working_dir: /app
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   ports:
  #     - "5173:5173"
  #   command: npm run dev -- --host
